services:
    postgres:
        container_name: postgres
        hostname: postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - dev_network

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        entrypoint: redis-server --appendonly yes --requirepass root --maxmemory 512mb --maxmemory-policy allkeys-lru
        networks:
            - dev_network
        ports:
            - 6379:6379
        volumes:
            - redis-data:/var/lib/redis

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - dev_network

volumes:
    pgdata:
    redis-data:

networks:
    dev_network:
